### ISSUE TITLE
Logo del footer

### ISSUE THREAD

**Issue by castromaciel** [sergiohomet/proyecto-3-grupo-2-front#20]
## Proceso:

1. Footer
2. Navegación hasta el footer

## Resultado esperado:

El logo del footer tiene que llevar al usuario hasta el inicio de la página o a la página de error.

## Resultado actual:

El logo del footer no tiene función alguna.

## Capturas 
![image](https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/2ef06c38-3bff-4447-9837-15806cd36b74)

**Comment by franciscojvicente** [comment]
Buenas tardes, Maciel!
Te dejo el código del commit. Saludos!
Código: c6d4f0f

**Comment by castromaciel** [comment]
Se valida la solución

Como recomendación, para mejorar el historial de cambios y versionamiento; lo ideal es solucionar un issue por pr.

Esto quiere decir que en este commit https://github.com/sergiohomet/proyecto-3-grupo-2-front/commit/c6d4f0f3684dd4969c5e5e7a620a68bddb443934 ya fue solucionado el issue [Links del footer #23
](https://github.com/sergiohomet/proyecto-3-grupo-2-front/issues/23)
