### ISSUE TITLE
Ubicación del Clima

### ISSUE THREAD

**Issue by castromaciel** [sergiohomet/proyecto-3-grupo-2-front#21]
## Resultado esperado

Se espera ver la información del clima en la parte superior. En uno de los costados
<img width="1290" alt="image" src="https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/ce0b2e29-f230-4fd4-b73b-9f30f231c051">

## Resultado actual

Actualmente, está tapando la imagen del Hero

## Captura

<img width="551" alt="image" src="https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/27786146-acab-497c-8af0-223ee583083f">

<img width="1436" alt="image" src="https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/c5eef17f-499e-4b77-b1f5-966e310c3363">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

<hr />

## Recomendación:

Eliminar la clase `m-auto` del contenedor del clima

<img width="1146" alt="image" src="https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/0e14663b-2b0f-4324-9132-4b7e78b55c14">

**Comment by goncalhurtado** [comment]
Buenas noches!
Ahí solucioné los inconvenientes mencionados. 
Te dejo el código del commit 82c70fa 
Saludos!

**Comment by castromaciel** [comment]
Se valida la solución
