### ISSUE TITLE
Permite añadir turno fecha antigua

### ISSUE THREAD

**Issue by castromaciel** [sergiohomet/proyecto-3-grupo-2-front#22]
## Proceso

1. Iniciar sesión
2. Dirigirse a turnos
3. Diligenciar los campos
4. Añadir turno

## Resultado esperado

Se espera poder registrar un turno a una fecha posterior.

## Resultado actual

Si bien, permite la creación de turnos, se debe validar que no permita la creación de turnos para fechas antiguas

## Captura

<img width="1131" alt="image" src="https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/1cfc88a8-1541-476f-afa5-3557d38c7e47">

<img width="1133" alt="image" src="https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/8a0ae1eb-d8c8-41d3-b78f-965462841e27">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by sergiohomet** [comment]
The commit 4523f85 solved the issue and changes already stay on main.

**Comment by castromaciel** [comment]
Se valida la solución
