### ISSUE TITLE
Links del footer

### ISSUE THREAD

**Issue by castromaciel** [sergiohomet/proyecto-3-grupo-2-front#23]
## Proceso

1. Dirigrise al footer
2. Intentar hacer click en las redes sociales

## Resultado esperado

Se esperaba que tanto nombres como logo de las redes sociales sean funcionales para el usuario.

## Resultado actual

Actualmente solo los logos tienen funcion

## Captura

![image](https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/d27a84be-2352-43d9-be52-88ac44e378ff)

![image](https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/bd206c30-6e14-4800-9c09-20c23c227a64)

https://github.com/sergiohomet/proyecto-3-grupo-2-front/assets/83432755/aa6c51eb-3eb3-4e08-bc24-38a29f0e5101

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by franciscojvicente** [comment]
Buenas tardes, Maciel!
Te dejo el código del commit. Saludos!
cödigo: c6d4f0f

**Comment by castromaciel** [comment]
Se valida la solución del defecto
